[package]

name = "tetnus"
version = "0.1.0"
authors = ["Avery Wagar <avery@wagar.cc>"]

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["winsock2", "winnt", "std"]}



[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
